### ISSUE TITLE
failed to npm run start

### ISSUE THREAD

**Issue by DreamPWJ** [Blazity/next-saas-starter#17]
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
Error: Could not find a production build in the 'E:\repo\landing-page-next\.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (E:\repo\landing-page-next\node_modules\next\dist\server\next-server.js:130:23)
    at new Server (E:\repo\landing-page-next\node_modules\next\dist\server\base-server.js:92:29)
    at new NextNodeServer (E:\repo\landing-page-next\node_modules\next\dist\server\next-server.js:74:9)
    at NextServer.createServer (E:\repo\landing-page-next\node_modules\next\dist\server\next.js:111:16)
    at async E:\repo\landing-page-next\node_modules\next\dist\server\next.js:123:31
child process exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

**Comment by DreamPWJ** [comment]
How to do SEO, fill in the key in meta there

**Comment by DreamPWJ** [comment]
support react18 ?

**Comment by bmstefanski** [comment]
> ready - started server on 0.0.0.0:3000, url: http://localhost:3000 warn - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled Error: Could not find a production build in the 'E:\repo\landing-page-next.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id at NextNodeServer.getBuildId (E:\repo\landing-page-next\node_modules\next\dist\server\next-server.js:130:23) at new Server (E:\repo\landing-page-next\node_modules\next\dist\server\base-server.js:92:29) at new NextNodeServer (E:\repo\landing-page-next\node_modules\next\dist\server\next-server.js:74:9) at NextServer.createServer (E:\repo\landing-page-next\node_modules\next\dist\server\next.js:111:16) at async E:\repo\landing-page-next\node_modules\next\dist\server\next.js:123:31 child process exited with code 1 error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> Process finished with exit code 1

Hi, please try `yarn build && yarn dev`



> How to do SEO, fill in the key in meta there, index.html meta name="keywords" meta name="description"

You can edit meta tags in the appropriate page file, for example, https://github.com/Blazity/next-saas-starter/blob/master/pages/index.tsx#L21 for homepage





> support react18 ?

currently it does not support react 18

**Comment by DreamPWJ** [comment]
thank you very much
