### ISSUE TITLE
how to make next-dark-theme default 🙏

### ISSUE THREAD

**Issue by AliceonFire** [Blazity/next-saas-starter#44]
How would I make this theme default to dark mode? Changing the `className` in `_document.tsx` shows the change when viewing source in browser, but still shows as "next-light-theme" when using "Inspect Element" browser function to view the rendered DOM.

https://github.com/Blazity/next-saas-starter/blob/375ae1bdbceac9799b849d5951b41e884074b98a/pages/_document.tsx#L37

**Comment by bmstefanski** [comment]
Hi, please try using this snippet and place it before this line https://github.com/Blazity/next-saas-starter/blob/master/pages/_app.tsx#L48

```jsx
<script dangerouslySetInnerHTML={{ __html: `localStorage.setItem("nextColorMode", "dark");` }} />
```

Also, remember to change the `next-light-theme` to `next-dark-theme` in _document :)

**Comment by bmstefanski** [comment]
cc @AliceonFire

**Comment by AliceonFire** [comment]
Thank you for the quick response with a working solution, @bmstefanski.
