### ISSUE TITLE
How to remove watermark popup?

### ISSUE THREAD

**Issue by mrtknrt** [Blazity/next-saas-starter#47]
How can I remove this? Do I have to pay for the theme?

![image](https://user-images.githubusercontent.com/19364945/202501617-a1f89691-7f02-418e-b0a9-6e684a2aec59.png)

**Comment by bmstefanski** [comment]
Hi @mrtknrt you can just revert [this commit ](https://github.com/Blazity/next-saas-starter/commit/66b927ffbf24835517aa8e779b09df113b8a21f2) or remove it manually from the _app file

**Comment by mrtknrt** [comment]
> Hi @mrtknrt you can just revert [this commit ](https://github.com/Blazity/next-saas-starter/commit/66b927ffbf24835517aa8e779b09df113b8a21f2) or remove it manually from the _app file. Everything here is free, you can modify the theme as much as you want

thank you sir
