### ISSUE TITLE
[Feature Request] Next 13

### ISSUE THREAD

**Issue by igor-h** [Blazity/next-saas-starter#74]
Hi ! 
Is somewhere in the roadmap to merge this template from Next 12 to NextJS 13?

Thanks for the information!

**Comment by igor-h** [comment]
Hi guys!  @bmstefanski @ilasota @logan-anderson @jamespohalloran 

Do you know guys anything about if is possible upgrade from next version 12 to 13?

Thank you

**Comment by bmstefanski** [comment]
Hi @igor-h, we are not planning on moving this template to Next v13, we believe that it wouldnt be beneficial, even if used with app directory, since it is a simple marketing page. 

You can follow us though, because there will are new templates incoming :)!

**Comment by igor-h** [comment]
@bmstefanski  Wow great! 

How can I follow you guys, and where can I find them? :)
I made that question just for curiosity! As I seen all the new things came in Next13

As well, can I contribute to future projects too? 👍🏽 
Thanks! 😃

**Comment by bmstefanski** [comment]
@igor-h the best place is probably linkedin. We announce every open source project there :) 

you can also follow the organization on github, then all new repos will apear on your github homepage 

Cheers
